version: '2'
services:
 alfresco:
  build: ./alfresco
  links:
   - solr6
   - libreoffice
  ports:
   - "8080:8080"
   - "2121:21"
   - "2525:25"
   - "1143:143"
   - "1139:139"
   - "1445:445"
  user: root
  privileged: true

 db:
  build: ./postgres
  network_mode: service:alfresco
  environment:
   - POSTGRES_DB=alfresco
   - POSTGRES_USER=alfresco
   - POSTGRES_PASSWORD=alfresco

 solr6:
  image: keensoft/alfresco-solr6:201701-GA
  ports:
   - 8983:8983

 libreoffice:
  image: xcgd/libreoffice